---
- name: add jenkins_group
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
  with_items: "{{ jenkins_groups }}"
  when: ansible_os_family != 'Alpine'

- name: add jenkins_user
  user:
    name: "{{ jenkins_user }}"
    uid: "{{ jenkins_uid }}"
    home: "{{ jenkins_home }}"
    groups: "{{ jenkins_groups | map(attribute='name') | list }}"
    shell: "{{ jenkins_user_shell }}"
  when: ansible_os_family != 'Alpine'

- name: add jenkins_group for Alpine
  import_tasks: Alpine.yml
  when: ansible_os_family == 'Alpine'
